version: '3'

services:
  workers:
    build:
      context: .
      dockerfile: dockerfile
    image: workers
    volumes:
      - .:/home/crawler
    depends_on:
      - redis
    command: ./docker-entrypoint.sh
  

  redis:
    #hostname: crawler_redis
    image: redis
    ports: 
      - "6379:6379"
  
  postgres:
    build:
      context: ./db
      dockerfile: dockerfile
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=crawlerdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser
    #command: ./docker-initdb.sh
